import { NextRequest, NextResponse } from "next/server";
import { formatTodoListForEmail, formatTranscriptForEmail } from "@/services/email";
import { TodoList } from "@/types/todo";

export async function POST(request: NextRequest) {
  console.log("[send-email/route.ts]: Email send request received");

  try {
    const { transcript, todoList } = await request.json();

    if (!transcript || !todoList) {
      return NextResponse.json(
        { error: "Missing transcript or todoList" },
        { status: 400 }
      );
    }

    const recipientEmail = process.env.RECIPIENT_EMAIL;
    const emailProvider = process.env.EMAIL_PROVIDER || "resend"; // resend, sendgrid, or nodemailer

    if (!recipientEmail) {
      return NextResponse.json(
        { error: "RECIPIENT_EMAIL not configured in environment variables" },
        { status: 500 }
      );
    }

    // Format the email content
    const transcriptHtml = formatTranscriptForEmail(transcript);
    const todoListHtml = formatTodoListForEmail(todoList as TodoList);

    const emailHtml = `
      <!DOCTYPE html>
      <html>
        <head>
          <meta charset="utf-8">
          <title>Call Transcription & Analysis</title>
        </head>
        <body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 800px; margin: 0 auto; padding: 20px;">
          <h1 style="color: #1e40af; border-bottom: 3px solid #3b82f6; padding-bottom: 10px;">Call Transcription & Analysis</h1>
          
          <h2 style="color: #2563eb; margin-top: 30px;">📝 Transcript</h2>
          ${transcriptHtml}
          
          <h2 style="color: #16a34a; margin-top: 30px;">✅ Todo List & Key Points</h2>
          ${todoListHtml}
          
          <hr style="margin: 40px 0; border: none; border-top: 1px solid #e5e7eb;">
          <p style="color: #6b7280; font-size: 14px; text-align: center;">
            Generated by Call Transcription & Analysis System<br>
            Powered by OpenAI Whisper & GPT-4
          </p>
        </body>
      </html>
    `;

    // Send email based on provider
    if (emailProvider === "resend") {
      await sendEmailWithResend(recipientEmail, emailHtml);
    } else if (emailProvider === "sendgrid") {
      await sendEmailWithSendGrid(recipientEmail, emailHtml);
    } else if (emailProvider === "nodemailer") {
      await sendEmailWithNodemailer(recipientEmail, emailHtml);
    } else {
      return NextResponse.json(
        { error: `Unsupported email provider: ${emailProvider}` },
        { status: 500 }
      );
    }

    console.log("[send-email/route.ts]: Email sent successfully");
    return NextResponse.json({ 
      success: true, 
      message: `Email sent successfully to ${recipientEmail}` 
    });

  } catch (error: unknown) {
    console.error("[send-email/route.ts]: Error sending email:", error);
    const errorMessage = error instanceof Error ? error.message : "Failed to send email";
    return NextResponse.json(
      { error: errorMessage },
      { status: 500 }
    );
  }
}

async function sendEmailWithResend(to: string, html: string) {
  const apiKey = process.env.RESEND_API_KEY;
  const fromEmail = process.env.FROM_EMAIL || "onboarding@resend.dev";

  if (!apiKey) {
    throw new Error("RESEND_API_KEY not configured");
  }

  const response = await fetch("https://api.resend.com/emails", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${apiKey}`,
    },
    body: JSON.stringify({
      from: fromEmail,
      to: [to],
      subject: "Call Transcription & Analysis Report",
      html: html,
    }),
  });

  if (!response.ok) {
    const error = await response.json();
    throw new Error(`Resend API error: ${JSON.stringify(error)}`);
  }

  return await response.json();
}

async function sendEmailWithSendGrid(to: string, html: string) {
  const apiKey = process.env.SENDGRID_API_KEY;
  const fromEmail = process.env.FROM_EMAIL;

  if (!apiKey || !fromEmail) {
    throw new Error("SENDGRID_API_KEY or FROM_EMAIL not configured");
  }

  const response = await fetch("https://api.sendgrid.com/v3/mail/send", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${apiKey}`,
    },
    body: JSON.stringify({
      personalizations: [{ to: [{ email: to }] }],
      from: { email: fromEmail },
      subject: "Call Transcription & Analysis Report",
      content: [{ type: "text/html", value: html }],
    }),
  });

  if (!response.ok) {
    const error = await response.text();
    throw new Error(`SendGrid API error: ${error}`);
  }
}

async function sendEmailWithNodemailer(to: string, html: string) {
  // For Nodemailer, you would need to install the package first
  // This is a placeholder - you'll need to uncomment and use it if you choose nodemailer
  throw new Error(
    "Nodemailer requires npm package installation. Please use 'resend' or 'sendgrid' instead, or install nodemailer package."
  );
  
  /* Example nodemailer implementation:
  const nodemailer = require('nodemailer');
  
  const transporter = nodemailer.createTransport({
    host: process.env.SMTP_HOST,
    port: process.env.SMTP_PORT,
    secure: true,
    auth: {
      user: process.env.SMTP_USER,
      pass: process.env.SMTP_PASSWORD,
    },
  });

  await transporter.sendMail({
    from: process.env.FROM_EMAIL,
    to: to,
    subject: "Call Transcription & Analysis Report",
    html: html,
  });
  */
}

